### ISSUE TITLE
Build error after updating ubuntu

### ISSUE THREAD

**Issue by mlp1802** [EmbarkStudios/physx-rs#200]
After upgrading ubuntu to 22 I get this error:
physx-sys-0.4.16/PhysX/pxshared/include/foundation/PxPreprocessor.h:35:10: fatal error: 'ciso646' file not found

I'm using physx 4.2. It seems that this file is not included in the new c++ compiler (or something). Is there no way around it?

**Comment by mlp1802** [comment]
UPDATE I cloned the project and tried to build it, same error. I'm not sure it can be build on newest ubuntu anymore.

**Comment by mlp1802** [comment]
Installing g++-11 and running export CXX=g++-11 fixed it

**Comment by mlp1802** [comment]
Can this be moved to somewhere else? would be nice having it up so someone else might see it, so I'm not closing the issue.

**Comment by tgolsson** [comment]
I'm going to guess `export CXX=g++-11` isn't the important part; rather that installing g++-11 also installed `libstdc++` which you were missing.

**Comment by mlp1802** [comment]
I resolved it somehow but I'm not sure how, after 12 hours of installing packages and compilers it suddenly worked.

**Comment by numfin** [comment]
@tgolsson @mlp1802 solution for me was:
`sudo apt install libc++-11-dev`
`export CXX=g++-11`
